### ISSUE TITLE
Register on bower

### ISSUE THREAD

**Issue by marcandre** [vbardales/chai-properties#1]
Hi, and thanks for this.
I'm just starting with chai and couldn't believe it's not in the default assertions, TBH.
If you could register your lib on bower it could be helpful.
Thanks!

**Comment by vbardales** [comment]
Hi !

In fact, I'm rather unhappy with bower, but I understand, going to watch about it :)

**Comment by vbardales** [comment]
I firmly disagree with the use of bower, but for bower-likers, chai-properties now exists on bower

**Comment by marcandre** [comment]
Thanks!
