### ISSUE TITLE
Support Chai 4

### ISSUE THREAD

**Issue by rjoonas** [vbardales/chai-properties#15]
[Chai 4 has been out for a while](http://chaijs.com/releases/) but chai-properties [requires Chai <4](https://github.com/vbardales/chai-properties/blob/c7f1b33e4a7dbc08313af96e251234155c6701cb/package.json#L22).

**Comment by CurtisHumphrey** [comment]
I've been using it with Chai 4 without issue

**Comment by PeterDaveHello** [comment]
but the dependency in package.json requires Chai < 4, so maybe it should be updated?

**Comment by vbardales** [comment]
Gotta check it this afternoon. I'll release 1.3.0 then if validated by tests

**Comment by vbardales** [comment]
Done
